---
title: "Tutorial of sraster"
author: "William Martinez"
date: "05/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Origanizaing vectoor information 

```{r }

library(rgdal)
#setwd("C://IPSTERS")
file_shape = 'C:\\IPSTERS\\COS2015\\COS2015_v2_08_02_2019_clip.shp'
#legend = st_read(file_shape)

legend = rgdal::readOGR(file_shape)

#===============================
#random selection
#===============================
#Goal : stratified random selection of traing samples at level of polygon

set.seed(123)   #setting same random selection for testing
list_df_classes  = split(legend,legend$Legend)

strat_random_selection = function(x, n_samples){
  n = nrow(x)
  index = sample(1:n,n_samples,replace = FALSE)
  return(x[index,])
}

#list_df_query = lapply(list_df_classes,strat_random_selection, n_samples = 5)

#df_query = do.call("rbind",list_df_query)

#rm(list_df_query,list_df_classes,legend)


#file_raster = 'IM_20170405_843.tif'

#shapes = split(df_query,df_query$OBJECTID)

#list_crops = lapply(shapes,crop_raster,file_raster)


#a = values(raster('IM_20170405_843.tif'))


#===============================
#Rasterization
#===============================

#rasterize
#r <- raster(ncols = reg[1], nrows = reg[2])
#extent(r) <- extent(shape)
#r <- rasterize(shape, r)



```

